general:
  startup_commands: []
  shutdown_commands: []

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: 'monitor_focus'

  hide_method: 'cloak'

  # show only windows in currently visible workspaces (on any monitor)
  show_all_in_taskbar: false

gaps:
  scale_with_dpi: true

  inner_gap: '3px'
  outer_gap:
    top: '5px'
    right: '5px'
    bottom: '5px'
    left: '5px'

window_effects:
  # NOTE:
  # 1. hide_title_bar:
  #   -> remove title bar from the window's frame
  #   -> can cause rendering issues for some applications.
  # 2. corner-style:
  #   -> 'square' OR 'rounded' OR 'small_rounded'

  focused_window:
    border:
      enabled: true
      color: '#97879f'

    hide_title_bar:
      enabled: false

    corner_style:
      enabled: true
      style: 'square'

    transparency:
      enabled: false
      opacity: 1.0

  other_windows: # all other non-focused windows
    border:
      enabled: false
      color: '#2b272f'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: 'square'
    transparency:
      enabled: false
      opacity: 0.90625

window_behavior:
  initial_state: 'tiling'
  state_defaults:
    floating:
      centered: true
      shown_on_top: false

    fullscreen:
      maximized: false
      shown_on_top: false

workspaces:
  - name: '1'
  - name: '2'
  - name: '3'
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'
  - name: 'HOLD'

window_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }

keybindings:
  - commands: ['focus --direction left']
    bindings: ['alt+h']
  - commands: ['focus --direction right']
    bindings: ['alt+l']
  - commands: ['focus --direction up']
    bindings: ['alt+k']
  - commands: ['focus --direction down']
    bindings: ['alt+j']

  - commands: ['move --direction left']
    bindings: ['alt+shift+h']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j']

  - commands: ['size --width 67%']
    bindings: ['alt+back']
  - commands: ['size --width 50%']
    bindings: ['alt+shift+back']
  - commands: ['size --width 100%']
    bindings: ['alt+ctrl+back']

  # # Disables window management and all other keybindings until alt+shift+p
  # # is pressed again.
  # - commands: ['wm-toggle-pause']
  #   bindings: ['alt+shift+p']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']

  # # Change focus from tiling windows -> floating -> fullscreen.
  # - commands: ['wm-cycle-focus']
  #   bindings: ['alt+space']

  - commands: ['toggle-floating --centered']
    bindings: ['alt+f']
  - commands: ['set-tiling']
    bindings: ['alt+shift+f']

  - commands: ['toggle-fullscreen']
    bindings: ['alt+z']

  - commands: ['toggle-minimized']
    bindings: ['alt+q']
  - commands: ['close']
    bindings: ['alt+shift+q']

  - commands: ['wm-exit']
    bindings: ['alt+shift+e']

  - commands: ['wm-reload-config']
    bindings: ['alt+shift+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['alt+shift+w']

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  - commands: ['shell-exec alacritty']
    bindings: ['alt+enter']

  # # Focus the next/previous active workspace defined in `workspaces` config.
  # - commands: ['focus --next-active-workspace']
  #   bindings: ['alt+s']
  # - commands: ['focus --prev-active-workspace']
  #   bindings: ['alt+a']
  #
  # # Focus the workspace that last had focus.
  # - commands: ['focus --recent-workspace']
  #   bindings: ['alt+d']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['alt+1']
  - commands: ['focus --workspace 2']
    bindings: ['alt+2']
  - commands: ['focus --workspace 3']
    bindings: ['alt+3']
  - commands: ['focus --workspace 4']
    bindings: ['alt+4']
  - commands: ['focus --workspace 5']
    bindings: ['alt+5']
  - commands: ['focus --workspace 6']
    bindings: ['alt+6']
  - commands: ['focus --workspace 7']
    bindings: ['alt+7']
  - commands: ['focus --workspace 8']
    bindings: ['alt+8']
  - commands: ['focus --workspace 9']
    bindings: ['alt+9']
  - commands: ['focus --workspace HOLD']
    bindings: ['alt+p']

  - commands: ['move-workspace --direction left']
    bindings: ['alt+shift+left']
  - commands: ['move-workspace --direction right']
    bindings: ['alt+shift+right']
  - commands: ['move-workspace --direction up']
    bindings: ['alt+shift+up']
  - commands: ['move-workspace --direction down']
    bindings: ['alt+shift+down']

  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['alt+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['alt+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['alt+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['alt+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['alt+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['alt+shift+6']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['alt+shift+7']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['alt+shift+8']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['alt+shift+9']
  - commands:
    - 'move --workspace HOLD'
    - 'focus --workspace HOLD'
    - 'toggle-minimized'
    - 'focus --recent-workspace'
    bindings: ['alt+shift+p']
